[project]
name = "asdf-ghcup"
revision = "1.0"

[profiles.default]
GEMINI_API_KEY = { description = "Google Gemini API key", required = false }

[profiles.development]
# Development profile inherits all secrets from default profile
