---
name: build

on: push

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        runner:
          - macos-latest
          - ubuntu-latest
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Remove ghcup
        run: ghcup nuke
      - name: Check ghcup is not present
        run: ! command -v ghcup
      - name: Run tests
        run: ./test/bats/bin/bats -T test

  integration:
    strategy:
      matrix:
        runner:
          - macos-latest
          - ubuntu-latest
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Remove ghcup
        run: ghcup nuke
      - name: Check ghcup is not present
        run: ! command -v ghcup
      - name: Test plugin
        uses: asdf-vm/actions/plugin-test@v3
        with:
          plugin: ghc
          command: ghc --version
