---
name: CI

on: push

jobs:
  build:
    strategy:
      matrix:
        runner:
          - macos-latest
          - ubuntu-latest

    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: ./test/bats/bin/bats -T test/

  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: npm
      - run: npm install
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
